### ISSUE TITLE
Add fishing mortality harvest option to Build_Input_File accounting for catch proportion by fleet

### ISSUE THREAD

**Issue by JonBrodziak** [PIFSCstockassessments/2024-WCNPO-MLS-Rebuilding#10]

**Comment by JonBrodziak** [comment]
Added constant fishing mortality rate option with F by fleet based on catch proportion by fleet.
Tested code F option code "Build_Input_File_test_F.R" with sample test results in /test/harvest.
Constant F option works.
Next step is to set up and test the general case of a mixture of catch quota or F for all fleets by time period.

**Comment by JonBrodziak** [comment]
Added mixed harvest option with capacity to specify a total landings quota or a total fishing mortality by period. The total harvest rate is apportioned by fleet based on the catch proportion by fleet in the terminal year of the assessment, at present. The mixed harvest option has been tested. The test results are in the folder /Build_Input_File/test/harvest. This option can also be generalized to use a recent average catch proportion by fleet and a recent average selectivity by fleet.

**Comment by michellesculley** [comment]
I've also added the ability to extract F by fleet to the SS_to_AGEPRO function, so if you wanted to apportion total harvest by the proportion of F for each fleet, you should be able to do that as well.
