### ISSUE TITLE
Create milestones for Striped Marlin Rebuilding Project

### ISSUE THREAD

**Issue by JonBrodziak** [PIFSCstockassessments/2024-WCNPO-MLS-Rebuilding#3]
Draft milestones have been added to the Striped Marlin Rebuilding Project.
Please review and provide comments by early next week..

**Comment by JonBrodziak** [comment]
Would like to hold a project meeting at IRC on Tuesday next week.

**Comment by MOshima-PIFSC** [comment]
@JonBrodziak I see the milestones you laid out [here](https://docs.google.com/document/d/15cpXX-s_Lf97FiT8_ZRPe__2pZXBDBUR6QYt7IKVJxM/edit). Would you like to get together sometime next week to add them to the project board?
