### ISSUE TITLE
Add AGEPRO option to not save auxiliary output files

### ISSUE THREAD

**Issue by JonBrodziak** [PIFSCstockassessments/2024-WCNPO-MLS-Rebuilding#4]
AGEPRO uses auxiliary output files to record all out simulation results for subsequent summary. By default, these files are saved to the output folder after the AGEPRO run is complete. The output auxiliary files take up a lot of storage space. The issue is to change the output file logical StockSummaryFlag to have 3 options: 
case 1: Delete all auxiliary files
case 2: Delete stock numbers at age file and save all others (Recruitment, Spawning Biomass, ...)
case 3: Save all auxiliary output files

**Comment by JonBrodziak** [comment]
Revised AGEPRO code has been developed to implement the auxiliary output file options. Revised code is being tested.

**Comment by JonBrodziak** [comment]
All tests have been completed and passed. AGEPRO reference manual has been updated.
New version is in agepro-dev/bin and agepro-dev/src.

**Comment by JonBrodziak** [comment]
The agepro code has been successfully modified and tested to allow for 4 options to handle auxiliary output files. This includes a "no write" option which removes the auxiliary files prior to completion of a projection run.

**Comment by efletcherPIFSC** [comment]
Appending reference to completion of PIFSCstockassessments/agepro-dev#1 as resolution of issue.
